{{- if .Values.global.namespaces.enabled }}
{{- $mainContext := .Values }}
{{- range .Values.global.namespaces.list }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  labels:
    name: {{ .namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
{{- end }}
{{- if eq .Values.global.security.payloadAppNetworkRestrictionsEnabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traffic-to-coresvc-switchboard
  namespace: payload-app
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: coresvc
      podSelector:
        matchLabels:
          app: coresvc-switchboard
{{- end }}
{{- end }}