name: setup-tar-creation

on: 
    workflow_dispatch:
    push:
        branches:
        - main

env:
  REGISTRY: ghcr.io/microsoft
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-tar-file:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@km/add_structure
      with:
        env_file: ./env/spacefx.env
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and package tar file
      shell: bash
      run: |
        chmod +x ./.vscode/build_setup_tarball.sh

        cp ./config/channels/nightly.yaml ./config/nightly.yaml
        cp ./config/github/annotations/azure-orbital-space-sdk-setup.yaml ./config/azure-orbital-space-sdk-setup.yaml

        echo "Running ./.vscode/build_setup_tarball.sh"
        sudo bash ./.vscode/build_setup_tarball.sh
        
        sub_exit_code=${PIPESTATUS[0]}
        if [[ $sub_exit_code -gt 0 ]]; then
            echo "Previous step failed.  Troubleshoot"
            echo "Outputting log file..."
            cat /var/spacedev/logs/build_setup_tarball.sh.log
            echo ""
            exit 1
        fi
